[package]
name = "pipetui"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27"
ratatui = "0.26"
anyhow = "1"
crossbeam-channel = "0.5"
unicode-width = "0.1"
unicode-segmentation = "1"
dirs = "5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
